#pragma once
#include "../nclgl/OGLRenderer.h"
#include "../nclgl/Frustrum.h"
#include <vector>
class HeightMap;
class Camera;
class Mesh;
class Light;
class MeshAnimation;
class MeshMaterial;
class Matrix4;
class SceneNode;

class Renderer : public OGLRenderer {
public:
	Renderer(Window& parent);
	~Renderer(void);
	void RenderScene() override;
	void UpdateScene(float dt) override;
	void toggleCamera() { isCameraFree = !isCameraFree; }

protected:
	void DrawWater(float transparancy);
	void DrawSkybox();
	void DrawAnimations();
	void DrawShadowScene(Light* l);
	void checkMeshes();
	void checkTextures();
	void checkShaders();
	void checkBuffers();
	void setCameraNodes();
	void setVariables();
	void setNodes();
	void buildNodeLists(SceneNode* from);
	void sortNodeList();
	void drawNodes();
	void drawNode(SceneNode* n);
	void clearNodeLists();
	void checkAnimation();
	void checkModelMatrial();
	void checkCurrentCamera();
	void GenerateScreenTexture(GLuint &into, bool depth = false);
	void fillBuffers();
	void combineBuffers();
	void createPointLights();
	bool isCameraFree;
	bool isShadow = false;
	bool isMainScene;
	bool isTransScene;
	HeightMap* heightMap;
	Shader* reflectShader;
	Shader* skyboxShader;
	Shader* lightShader;
	Shader* characterShader;
	Shader* shadowShader;
	Shader* sceneShader;
	Shader* pointLightShader;
	Shader* combineShader;
	Shader* nodeShader;
	Shader* characterShadowShader;
	Light* light;
	Light* pointLights;
	Camera* activeCamera;
	Camera* freeCamera;
	Mesh* quad;
	Mesh* sphere;
	Mesh* Tree;
	Mesh* soldier;
	Mesh* UFO;
	Mesh* UFOBody;
	Mesh* UFOCockpit;
	SceneNode* landMapRoot;
	SceneNode* transSceneRoot;
	MeshAnimation* soldierAnimation;	
	MeshMaterial* soldierMaterial;
	MeshMaterial* TreeMaterial;
	MeshMaterial* UFOMaterial;
	MeshMaterial* UFOBodyMaterial;
	MeshMaterial* UFOCockpitMaterial;
	vector<GLuint> soldierMatTextures;
	vector<GLuint> TreeMatTextures;
	vector<GLuint> UFOMatTextures;
	vector<GLuint> UFOBodyMatTextures;
	vector<GLuint> UFOCockpitMatTextures;
	GLuint terrainTex;
	GLuint waterTex;
	GLuint cubeMap;
	GLuint terrainBump;
	GLuint shadowTex;
	GLuint shadowFBO;
	GLuint bufferFBO;
	GLuint pointLightFBO;
	GLuint bufferColourTex;
	GLuint bufferNormalTex;
	GLuint bufferDepthTex;
	GLuint lightDiffuseTex;
	GLuint lightSpecularTex;
	Matrix4 soldierModel;
	Vector3 soldierPos;
	Matrix4 TreeModel;
	Vector3 TreePos;
	Matrix4 UFOBodyModel;
	Vector3 UFOBodyPos;
	Vector3 UFOCockpitPos;
	Matrix4 UFOCockpitModel;
	float waterRotate;
	float waterCycle;
	int currentFrame;
	float frameTime;
	Frustrum frameFrustrum;
	vector<SceneNode*> transparentNodeList;
	vector<SceneNode*> nodeList;
};
